### ISSUE TITLE
The target entry-point "@netcreaties/ngx-smart-banner" has missing dependencies

### ISSUE THREAD

**Issue by hey24sheep** [RFreij/ngx-smart-banner#7]
Hi, I am facing this issue on Angular 9+ project. It says failed to compile with the following error. Could you please let me know how to fix this? If I do `npm i --save ngx-cookie-service` I can bypass this issue. Btw, I don't think you need that external dependency, why can't you just use document.cookie with their same validation? 

**edit** : looking at `peer dependency` I can see that it's user based requirement but if the project will fail compile time why not make it a normal dependency?

```
Failed to compile.

The target entry-point "@netcreaties/ngx-smart-banner" has missing dependencies:
 - ngx-cookie-service
```

**Comment by hey24sheep** [comment]
Well, installing peer dependency fixed my issue so I am closing it.

**Comment by RFreij** [comment]
@hey24sheep i've been thinking about removing the service dependency. It has been added because the application i originally made this for already had it included and i was being lazy.

However, that application doesn't use the package anymore. I'll do an update soon where i'll be using document.cookie.
